#!/bin/bash

alias pa='php artisan'
alias gs='git status'
alias ga='git add .'
alias gb='git branch'
alias gc='git commit -m'
alias gca='git commit -a'
alias gd='git diff'
alias go='git checkout'
alias gk='gitk --all&'
alias gx='gitx --all'
alias gp='git push'
alias gpu='git pull'
alias gpo='git push -u origin'
alias ni='npm install'
alias ci='composer install'
alias cls='clear'
alias flr='php artisan make:filament-resource'
alias queue='php artisan queue:listen'
alias model='php artisan make:model'
alias controller='php artisan make:controller'
alias policy='php artisan make:policy'
alias event='php artisan make:event'
